/* @flow */
// AUTHENTICATE EVENTS
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const RESTORE_SESSION = "RESTORE_SESSION";
export const RESTORE_REQUEST = "RESTORE_REQUEST";
export const RESTORE_FAILED = "RESTORE_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
